<?php

/* * *************************************************************
 * Extension Manager/Repository config file for ext: "videoportal"
 *
 * Auto generated by Extension Builder 2021-07-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 * ************************************************************* */

$EM_CONF[$_EXTKEY] = [
    'title' => 'Videoportal',
    'description' => 'Videoportal with a Video-Detail Section and a Video-List Section',
    'category' => 'plugin',
    'author' => 'Julian',
    'author_email' => 'julianrost@posteo.de',
    'state' => 'alpha',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
            'vhs' => '6.0.5'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
